// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/discount.proto

package discount

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetRequest struct {
	ProductID            string   `protobuf:"bytes,1,opt,name=productID,proto3" json:"productID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d27f2fd5df31734b, []int{0}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

type DiscountRatio struct {
	PreRequisite         int32    `protobuf:"varint,1,opt,name=preRequisite,proto3" json:"preRequisite,omitempty"`
	Entitled             int32    `protobuf:"varint,2,opt,name=entitled,proto3" json:"entitled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscountRatio) Reset()         { *m = DiscountRatio{} }
func (m *DiscountRatio) String() string { return proto.CompactTextString(m) }
func (*DiscountRatio) ProtoMessage()    {}
func (*DiscountRatio) Descriptor() ([]byte, []int) {
	return fileDescriptor_d27f2fd5df31734b, []int{1}
}

func (m *DiscountRatio) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscountRatio.Unmarshal(m, b)
}
func (m *DiscountRatio) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscountRatio.Marshal(b, m, deterministic)
}
func (m *DiscountRatio) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscountRatio.Merge(m, src)
}
func (m *DiscountRatio) XXX_Size() int {
	return xxx_messageInfo_DiscountRatio.Size(m)
}
func (m *DiscountRatio) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscountRatio.DiscardUnknown(m)
}

var xxx_messageInfo_DiscountRatio proto.InternalMessageInfo

func (m *DiscountRatio) GetPreRequisite() int32 {
	if m != nil {
		return m.PreRequisite
	}
	return 0
}

func (m *DiscountRatio) GetEntitled() int32 {
	if m != nil {
		return m.Entitled
	}
	return 0
}

type DiscountValue struct {
	Value                float32  `protobuf:"fixed32,1,opt,name=value,proto3" json:"value,omitempty"`
	RequiredProducts     int32    `protobuf:"varint,2,opt,name=requiredProducts,proto3" json:"requiredProducts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscountValue) Reset()         { *m = DiscountValue{} }
func (m *DiscountValue) String() string { return proto.CompactTextString(m) }
func (*DiscountValue) ProtoMessage()    {}
func (*DiscountValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_d27f2fd5df31734b, []int{2}
}

func (m *DiscountValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscountValue.Unmarshal(m, b)
}
func (m *DiscountValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscountValue.Marshal(b, m, deterministic)
}
func (m *DiscountValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscountValue.Merge(m, src)
}
func (m *DiscountValue) XXX_Size() int {
	return xxx_messageInfo_DiscountValue.Size(m)
}
func (m *DiscountValue) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscountValue.DiscardUnknown(m)
}

var xxx_messageInfo_DiscountValue proto.InternalMessageInfo

func (m *DiscountValue) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *DiscountValue) GetRequiredProducts() int32 {
	if m != nil {
		return m.RequiredProducts
	}
	return 0
}

type ProductDiscount struct {
	DiscountID           string         `protobuf:"bytes,1,opt,name=discountID,proto3" json:"discountID,omitempty"`
	Title                string         `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Summary              string         `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Type                 string         `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	DiscountRatio        *DiscountRatio `protobuf:"bytes,5,opt,name=discountRatio,proto3" json:"discountRatio,omitempty"`
	DiscountValue        *DiscountValue `protobuf:"bytes,6,opt,name=discountValue,proto3" json:"discountValue,omitempty"`
	ProductIDs           []string       `protobuf:"bytes,7,rep,name=productIDs,proto3" json:"productIDs,omitempty"`
	Allocationlimit      int32          `protobuf:"varint,8,opt,name=allocationlimit,proto3" json:"allocationlimit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ProductDiscount) Reset()         { *m = ProductDiscount{} }
func (m *ProductDiscount) String() string { return proto.CompactTextString(m) }
func (*ProductDiscount) ProtoMessage()    {}
func (*ProductDiscount) Descriptor() ([]byte, []int) {
	return fileDescriptor_d27f2fd5df31734b, []int{3}
}

func (m *ProductDiscount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductDiscount.Unmarshal(m, b)
}
func (m *ProductDiscount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductDiscount.Marshal(b, m, deterministic)
}
func (m *ProductDiscount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductDiscount.Merge(m, src)
}
func (m *ProductDiscount) XXX_Size() int {
	return xxx_messageInfo_ProductDiscount.Size(m)
}
func (m *ProductDiscount) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductDiscount.DiscardUnknown(m)
}

var xxx_messageInfo_ProductDiscount proto.InternalMessageInfo

func (m *ProductDiscount) GetDiscountID() string {
	if m != nil {
		return m.DiscountID
	}
	return ""
}

func (m *ProductDiscount) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ProductDiscount) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *ProductDiscount) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ProductDiscount) GetDiscountRatio() *DiscountRatio {
	if m != nil {
		return m.DiscountRatio
	}
	return nil
}

func (m *ProductDiscount) GetDiscountValue() *DiscountValue {
	if m != nil {
		return m.DiscountValue
	}
	return nil
}

func (m *ProductDiscount) GetProductIDs() []string {
	if m != nil {
		return m.ProductIDs
	}
	return nil
}

func (m *ProductDiscount) GetAllocationlimit() int32 {
	if m != nil {
		return m.Allocationlimit
	}
	return 0
}

type ListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d27f2fd5df31734b, []int{4}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

type ListResponse struct {
	Discounts            []*ProductDiscount `protobuf:"bytes,1,rep,name=discounts,proto3" json:"discounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d27f2fd5df31734b, []int{5}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetDiscounts() []*ProductDiscount {
	if m != nil {
		return m.Discounts
	}
	return nil
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "discount.GetRequest")
	proto.RegisterType((*DiscountRatio)(nil), "discount.DiscountRatio")
	proto.RegisterType((*DiscountValue)(nil), "discount.DiscountValue")
	proto.RegisterType((*ProductDiscount)(nil), "discount.ProductDiscount")
	proto.RegisterType((*ListRequest)(nil), "discount.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "discount.ListResponse")
}

func init() { proto.RegisterFile("proto/discount.proto", fileDescriptor_d27f2fd5df31734b) }

var fileDescriptor_d27f2fd5df31734b = []byte{
	// 383 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4d, 0x6b, 0xdb, 0x40,
	0x10, 0xb5, 0x2c, 0x7f, 0x69, 0x6c, 0xe3, 0x32, 0xb8, 0xed, 0xd6, 0x94, 0x22, 0xf6, 0x24, 0x7c,
	0x70, 0xc1, 0x3d, 0xb8, 0x97, 0xde, 0x0c, 0xa6, 0x10, 0x48, 0xb2, 0x81, 0xdc, 0x15, 0x69, 0x0f,
	0x0b, 0xb2, 0xa4, 0x68, 0x57, 0x06, 0xdf, 0xf3, 0xb7, 0xf2, 0xdf, 0xc2, 0xae, 0x2c, 0xad, 0xe4,
	0xe0, 0x9b, 0xde, 0xdb, 0x99, 0x37, 0x6f, 0x9e, 0x06, 0x96, 0x79, 0x91, 0xa9, 0xec, 0x77, 0x2c,
	0x64, 0x94, 0x95, 0xa9, 0xda, 0x18, 0x88, 0x93, 0x1a, 0xd3, 0x35, 0xc0, 0x81, 0x2b, 0xc6, 0x5f,
	0x4b, 0x2e, 0x15, 0xfe, 0x04, 0x2f, 0x2f, 0xb2, 0xb8, 0x8c, 0xd4, 0xff, 0x3d, 0x71, 0x7c, 0x27,
	0xf0, 0x98, 0x25, 0xe8, 0x3d, 0xcc, 0xf7, 0x97, 0x3e, 0x16, 0x2a, 0x91, 0x21, 0x85, 0x59, 0x5e,
	0x70, 0xdd, 0x2c, 0xa4, 0x50, 0xdc, 0x74, 0x0c, 0x59, 0x87, 0xc3, 0x15, 0x4c, 0x78, 0xaa, 0x84,
	0x4a, 0x78, 0x4c, 0xfa, 0xe6, 0xbd, 0xc1, 0xf4, 0xd1, 0x0a, 0x3e, 0x87, 0x49, 0xc9, 0x71, 0x09,
	0xc3, 0x93, 0xfe, 0x30, 0x4a, 0x7d, 0x56, 0x01, 0x5c, 0xc3, 0x97, 0x42, 0xeb, 0x15, 0x3c, 0x7e,
	0xa8, 0xcc, 0xc8, 0x8b, 0xd4, 0x27, 0x9e, 0xbe, 0xf7, 0x61, 0x71, 0x01, 0xb5, 0x34, 0xfe, 0x02,
	0xa8, 0xf7, 0x6d, 0xd6, 0x6a, 0x31, 0x7a, 0xaa, 0x31, 0x64, 0x44, 0x3d, 0x56, 0x01, 0x24, 0x30,
	0x96, 0xe5, 0xf1, 0x18, 0x16, 0x67, 0xe2, 0x1a, 0xbe, 0x86, 0x88, 0x30, 0x50, 0xe7, 0x9c, 0x93,
	0x81, 0xa1, 0xcd, 0x37, 0xfe, 0x83, 0x79, 0xdc, 0xce, 0x86, 0x0c, 0x7d, 0x27, 0x98, 0x6e, 0xbf,
	0x6f, 0x9a, 0xe4, 0x3b, 0xd1, 0xb1, 0x6e, 0x75, 0xbb, 0xdd, 0x24, 0x41, 0x46, 0xb7, 0xda, 0xcd,
	0x33, 0xeb, 0x56, 0xeb, 0x0d, 0x9b, 0xdf, 0x24, 0xc9, 0xd8, 0x77, 0xf5, 0x86, 0x96, 0xc1, 0x00,
	0x16, 0x61, 0x92, 0x64, 0x91, 0x9e, 0x95, 0x26, 0xe2, 0x28, 0x14, 0x99, 0x98, 0x00, 0xaf, 0x69,
	0x3a, 0x87, 0xe9, 0x9d, 0x90, 0xf5, 0x41, 0xd0, 0x03, 0xcc, 0x2a, 0x28, 0xf3, 0x2c, 0x95, 0x1c,
	0x77, 0xe0, 0xd5, 0x93, 0x25, 0x71, 0x7c, 0x37, 0x98, 0x6e, 0x7f, 0x58, 0x8f, 0x57, 0xc1, 0x33,
	0x5b, 0xbb, 0x7d, 0x73, 0x60, 0x51, 0xf3, 0x4f, 0xbc, 0x38, 0x89, 0x88, 0xe3, 0x5f, 0x70, 0x0f,
	0x5c, 0xe1, 0xd2, 0x0a, 0xd8, 0x53, 0x5c, 0xdd, 0x96, 0xa5, 0x3d, 0xdc, 0xc1, 0x40, 0xdb, 0xc2,
	0xaf, 0xb6, 0xa8, 0xe5, 0x7a, 0xf5, 0xed, 0x9a, 0xae, 0xdc, 0xd3, 0xde, 0xcb, 0xc8, 0xdc, 0xff,
	0x9f, 0x8f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x25, 0xff, 0x60, 0x10, 0x17, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for DiscountService service

type DiscountServiceClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*ProductDiscount, error)
	List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error)
}

type discountServiceClient struct {
	c           client.Client
	serviceName string
}

func NewDiscountServiceClient(serviceName string, c client.Client) DiscountServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "discount"
	}
	return &discountServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *discountServiceClient) Get(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*ProductDiscount, error) {
	req := c.c.NewRequest(c.serviceName, "DiscountService.Get", in)
	out := new(ProductDiscount)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discountServiceClient) List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error) {
	req := c.c.NewRequest(c.serviceName, "DiscountService.List", in)
	out := new(ListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DiscountService service

type DiscountServiceHandler interface {
	Get(context.Context, *GetRequest, *ProductDiscount) error
	List(context.Context, *ListRequest, *ListResponse) error
}

func RegisterDiscountServiceHandler(s server.Server, hdlr DiscountServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&DiscountService{hdlr}, opts...))
}

type DiscountService struct {
	DiscountServiceHandler
}

func (h *DiscountService) Get(ctx context.Context, in *GetRequest, out *ProductDiscount) error {
	return h.DiscountServiceHandler.Get(ctx, in, out)
}

func (h *DiscountService) List(ctx context.Context, in *ListRequest, out *ListResponse) error {
	return h.DiscountServiceHandler.List(ctx, in, out)
}
